const ACCOUNT_LOCK_TIME = 10 * 60 * 1000; // 10 minutes
const ACCOUNT_LOGIN_ATTEMPTS = 3;
const RESET_TOKEN_EXPIRATION_TIME = 10 * 60 * 1000; // 10 minutes

module.exports = {
  ACCOUNT_LOCK_TIME,
  ACCOUNT_LOGIN_ATTEMPTS,
  RESET_TOKEN_EXPIRATION_TIME,
};
